#!/bin/bash

VERSION=2.7.10b
PACKAGE=STAR
TOOL=STAR
DIRECTORY=$(dirname $0)

STORAGES=(/ocean /bil /hive /local)

OPTIONS=""
for STORAGE in "${STORAGES[@]}"
do
  	if [ -d "$STORAGE" ]; then
                OPTIONS=$OPTIONS" -B $STORAGE"
        fi
done

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif /opt/STAR_2.7.10b/Linux_x86_64_static/$TOOL "$@"
