#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=2.7.6a
PACKAGE=star
TOOL=STAR
DIRECTORY=/opt/packages/$PACKAGE/$VERSION

singularity exec -B /ocean $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
